name = "dense-ev"
url = "https://github.com/atlytle/dense-ev"
description = "Implements expectation value measurements in Qiskit using optimal dense grouping. Dense-ev provides an improvement of ~2^m over naive grouping and (3/2)^m over qubit-wise commuting groups. Based on arXiv:2305.11847."
licence = "Apache License 2.0"
contact_info = "atlytle@gmail.com"
alternatives = "_No response_"
affiliations = "University of Illinois at Urbana-Champaign"
labels = [ "Paper implementation",]
tier = "Community"
website = "https://github.com/atlytle/dense-ev"
styles_results = []
coverages_results = []
skip_tests = false
stars = 5
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324738.3635

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
qiskit_version = "0.44.1"
timestamp = 1696324796.047821

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
qiskit_version = "0.44.1"
timestamp = 1696324367.525503

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.42.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
qiskit_version = "0.42.1"
timestamp = 1696324794.869462

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
qiskit_version = "0.44.1"
timestamp = 1696324367.525503

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324738.3635

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.42.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390976578"
qiskit_version = "0.42.1"
timestamp = 1696324794.869462

