name = "Electronic Structure Orbital Optimization"
url = "https://github.com/JoelHBierman/electronic-structure-orbital-optimization"
description = "Apply orbital optimization to quantum algorithms that solve electronic structure Hamiltonians. This collection of methods optimize the underlying basis set through orbital rotations, finding more accurate energies with fewer qubits."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334243"
package_commit_hash = "937ca5b313f66ec36922bffb4b474474478ce729"
qiskit_version = ""
timestamp = 1706001198.714688

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.2"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334243"
qiskit_version = "0.45.2"
timestamp = 1706001044.300676

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.2"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334243"
qiskit_version = "0.45.2"
timestamp = 1706001410.750365

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.2"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334243"
qiskit_version = "0.45.2"
timestamp = 1706001410.750365

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.2"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334243"
qiskit_version = "0.45.2"
timestamp = 1706001044.300676

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334243"
package_commit_hash = "937ca5b313f66ec36922bffb4b474474478ce729"
qiskit_version = ""
timestamp = 1706001198.714688

