name = "mirror-gates"
url = "https://github.com/Pitt-JonesLab/mirror-gates"
description = "MIRAGE is a transpilation plugin for quantum circuits that minimizes the use of SWAP gates while optimizing native basis gate decomposition through mirror gates. Specifically designed for iSWAP-based quantum systems, MIRAGE improves circuit depth, making quantum algorithms more practical and efficient."
licence = "MIT license"
contact_info = "evmckinney9@gmail.com"
alternatives = "_No response_"
affiliations = "University of Pittsburgh"
labels = [ "Transpiler plugin", "Paper implementation",]
tier = "Community"
website = "https://arxiv.org/abs/2308.03874"
styles_results = []
coverages_results = []
skip_tests = false
stars = 2
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324684.538802

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
qiskit_version = "0.44.1"
timestamp = 1696324723.555883

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
qiskit_version = "0.44.1"
timestamp = 1696324339.117834

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
qiskit_version = "0.44.1"
timestamp = 1696324722.383852

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
qiskit_version = "0.44.1"
timestamp = 1696324339.117834

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324684.538802

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977729"
qiskit_version = "0.44.1"
timestamp = 1696324722.383852

