name = "mirror-gates"
url = "https://github.com/Pitt-JonesLab/mirror-gates"
description = "MIRAGE is a transpilation plugin for quantum circuits that minimizes the use of SWAP gates while optimizing native basis gate decomposition through mirror gates. Specifically designed for iSWAP-based quantum systems, MIRAGE improves circuit depth, making quantum algorithms more practical and efficient."
licence = "MIT license"
contact_info = "evmckinney9@gmail.com"
alternatives = "_No response_"
affiliations = "University of Pittsburgh"
labels = [ "Transpiler plugin", "Paper implementation",]
tier = "Community"
website = "https://arxiv.org/abs/2308.03874"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
group = "other"
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
package_commit_hash = "45e42525224e9e1857300e7e5529273fe619c9e4"
qiskit_version = "1.0.0"
timestamp = 1700557785.268616

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
qiskit_version = "0.45.0"
timestamp = 1700557817.956577

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
qiskit_version = "0.45.0"
timestamp = 1700557455.70405

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
qiskit_version = "0.45.0"
timestamp = 1700557815.98516

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543442"
qiskit_version = "0.44.1"
timestamp = 1695719974.491691

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543442"
qiskit_version = "0.44.1"
timestamp = 1695719534.001157

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545038402"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534336.658552

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756541"
qiskit_version = "0.44.2"
timestamp = 1698139199.340997

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756541"
qiskit_version = "0.44.2"
timestamp = 1698138764.001804

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
qiskit_version = "0.45.0"
timestamp = 1700557815.98516

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
qiskit_version = "0.45.0"
timestamp = 1700557455.70405

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941512933"
package_commit_hash = "45e42525224e9e1857300e7e5529273fe619c9e4"
qiskit_version = "1.0.0"
timestamp = 1700557785.268616

