name = "PurpleCaffeine"
url = "https://github.com/IceKhan13/purplecaffeine"
description = "Project is aimed to create simple general interface to track quantum experiments, store and search them in an easy way."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "QAMP"
labels = [ "Productivity", "Jupyter notebook",]
created_at = 1688661859.080258
updated_at = 1688661859.080264
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 6
group = "other"
documentation = "https://icekhan13.github.io/purplecaffeine/index.html"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396710.148

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
qiskit_version = "0.45.1"
timestamp = 1705396800.749031

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
qiskit_version = "0.45.1"
timestamp = 1705396574.013905

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
qiskit_version = "0.45.1"
timestamp = 1705396798.776012

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543781"
qiskit_version = "0.44.1"
timestamp = 1695719671.169195

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543781"
qiskit_version = "0.44.1"
timestamp = 1695720141.771474

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545035463"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534512.954835

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755024"
qiskit_version = "0.44.2"
timestamp = 1698139707.001367

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755024"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139579.821144

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755024"
qiskit_version = "0.44.2"
timestamp = 1698138965.979135

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
qiskit_version = "0.45.1"
timestamp = 1705396798.776012

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
qiskit_version = "0.45.1"
timestamp = 1705396574.013905

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539252604"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396710.148

