name = "pyRiemann-qiskit"
url = "https://github.com/pyRiemann/pyRiemann-qiskit"
description = "A library for supervised machine learning based on quantum computing and Riemannian geometry. The project is built on top of the Qiskit and pyRiemann projects and focuses on the classification of time series data."
licence = "BSD 3-Clause \"New\" or \"Revised\" license"
contact_info = "gcattan@hotmail.fr"
alternatives = "_No response_"
affiliations = "pyRiemann (https://github.com/pyRiemann)"
labels = [ "Machine learning",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 18
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396337.739597

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
qiskit_version = "0.45.0"
timestamp = 1705396392.567141

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
qiskit_version = "0.45.0"
timestamp = 1705396213.957448

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
qiskit_version = "0.45.0"
timestamp = 1705396390.640483

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
qiskit_version = "0.45.0"
timestamp = 1705396390.640483

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
qiskit_version = "0.45.0"
timestamp = 1705396213.957448

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251211"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396337.739597

