name = "qiskit-aqt-provider"
url = "https://github.com/qiskit-community/qiskit-aqt-provider"
description = "Qiskit provider for ion-trap quantum computers from Alpine Quantum Technologies (AQT). https://www.aqt.eu/qc-systems/"
licence = "Apache License 2.0"
contact_info = "info@aqt.eu"
alternatives = "_No response_"
affiliations = "Alpine Quantum Technologies GmbH"
labels = [ "Provider",]
tier = "Community"
website = "https://qiskit-community.github.io/qiskit-aqt-provider/"
styles_results = []
coverages_results = []
skip_tests = false
group = "provider"
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348751.864615

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
qiskit_version = "0.45.0"
timestamp = 1699348783.898082

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
qiskit_version = "0.45.0"
timestamp = 1699348340.221012

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.43.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
qiskit_version = "0.43.3"
timestamp = 1699348781.581346

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757109"
qiskit_version = "0.44.2"
timestamp = 1698138760.205501

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.43.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
qiskit_version = "0.43.3"
timestamp = 1699348781.581346

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
qiskit_version = "0.45.0"
timestamp = 1699348340.221012

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782295426"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348751.864615

