name = "qiskit-aqt-provider"
url = "https://github.com/qiskit-community/qiskit-aqt-provider"
description = "Qiskit provider for ion-trap quantum computers from Alpine Quantum Technologies (AQT). https://www.aqt.eu/qc-systems/"
licence = "Apache License 2.0"
contact_info = "info@aqt.eu"
alternatives = "_No response_"
affiliations = "Alpine Quantum Technologies GmbH"
labels = [ "Provider",]
tier = "Community"
website = "https://qiskit-community.github.io/qiskit-aqt-provider/"
styles_results = []
coverages_results = []
skip_tests = false
stars = 25
group = "provider"
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
package_commit_hash = "45e42525224e9e1857300e7e5529273fe619c9e4"
qiskit_version = "1.0.0"
timestamp = 1700557772.740394

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
qiskit_version = "0.45.0"
timestamp = 1700557796.938378

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
qiskit_version = "0.45.0"
timestamp = 1700557445.348815

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
qiskit_version = "0.45.0"
timestamp = 1700557795.981131

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.43.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757109"
qiskit_version = "0.43.3"
timestamp = 1698139164.804802

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757109"
qiskit_version = "0.44.2"
timestamp = 1698138760.205501

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
qiskit_version = "0.45.0"
timestamp = 1700557445.348815

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
qiskit_version = "0.45.0"
timestamp = 1700557795.981131

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6941513000"
package_commit_hash = "45e42525224e9e1857300e7e5529273fe619c9e4"
qiskit_version = "1.0.0"
timestamp = 1700557772.740394

