name = "Qiskit Qulacs"
url = "https://github.com/Gopal-Dahale/qiskit-qulacs"
description = "Qiskit-Qulacs allows users to execute Qiskit programs using Qulacs backend."
licence = "Apache License 2.0"
contact_info = "dahalegopal27@gmail.com"
alternatives = "_No response_"
affiliations = "Supported by the Unitary Fund microgrant program: https://unitary.fund/grants/"
labels = [ "Circuit simulator", "Converter", "Provider",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
group = "provider"
documentation = "https://qiskit-qulacs.netlify.app/"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539253322"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396714.942488

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539253322"
qiskit_version = "0.45.1"
timestamp = 1705396561.643028

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539253322"
qiskit_version = "0.45.1"
timestamp = 1705396766.094987

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539253322"
qiskit_version = "0.45.1"
timestamp = 1705396561.643028

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539253322"
qiskit_version = "0.45.1"
timestamp = 1705396766.094987

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539253322"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396714.942488

