name = "Qiskit QEC"
url = "https://github.com/qiskit-community/qiskit-qec"
description = "For developers, experimentalists, and theorists of quantum error correction."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Algorithms", "Error correction", "Circuit",]
created_at = 1662992390.122591
updated_at = 1662992390.122597
tier = "Extensions"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 50
group = "other"
