name = "qiskit-classroom"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom"
description = "Qiskit-classroom is a toolkit that helps implement quantum algorithms by converting and visualizing different expressions used in the Qiskit ecosystem using Qiskit-classroom-converter. The following three transformations are supported : Quantum Circuit to Dirac notation, Quantum Circuit to Matrix, Matrix to Quantum Circuit etc..."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Visualization",]
tier = "Community"
website = "https://github.com/KMU-quantum-classroom"
styles_results = []
coverages_results = []
skip_tests = false
stars = 1
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
package_commit_hash = "e91947e1b55f6e661c683fba72ab66c5f92d3aec"
qiskit_version = ""
timestamp = 1701162639.391388

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
qiskit_version = "0.45.0"
timestamp = 1701162683.319953

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
qiskit_version = "0.45.0"
timestamp = 1701162282.666687

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
qiskit_version = "0.44.1"
timestamp = 1701162680.339328

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545378"
qiskit_version = "0.44.1"
timestamp = 1695719559.39801

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545042072"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535040.818637

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758746"
qiskit_version = "0.44.2"
timestamp = 1698139332.539176

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758746"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139755.818676

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
package_commit_hash = "e91947e1b55f6e661c683fba72ab66c5f92d3aec"
qiskit_version = ""
timestamp = 1701162639.391388

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
qiskit_version = "0.44.1"
timestamp = 1701162680.339328

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431636"
qiskit_version = "0.45.0"
timestamp = 1701162282.666687

