name = "qiskit-metal-docker"
url = "https://github.com/Dpbm/qiskit-metal-docker"
description = "A Docker image to run Qiskit Metal projects."
licence = "MIT license"
contact_info = "dpbm136@gmail.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Hardware",]
tier = "Community"
website = "https://dpbm.github.io/qiskit-metal-docker/"
styles_results = []
coverages_results = []
skip_tests = false
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334871"
package_commit_hash = "937ca5b313f66ec36922bffb4b474474478ce729"
qiskit_version = "unknown"
timestamp = 1706000932.002238

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334871"
qiskit_version = "unknown"
timestamp = 1706000926.566286

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334871"
qiskit_version = "unknown"
timestamp = 1706000937.327008

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334871"
package_commit_hash = "937ca5b313f66ec36922bffb4b474474478ce729"
qiskit_version = "unknown"
timestamp = 1706000932.002238

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334871"
qiskit_version = "unknown"
timestamp = 1706000926.566286

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7623334871"
qiskit_version = "unknown"
timestamp = 1706000937.327008

