name = "qiskit-classroom-converter"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom-converter"
description = "Convert quantum circuits, matrices, and bra-ket strings. This converter includes the following conversion functions: quantum circuit to bra-ket notation, quantum circuit to matrix, matrix to quantum circuit, bra-ket notation to matrix"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Converter",]
tier = "Community"
website = "https://github.com/KMU-quantum-classroom"
styles_results = []
coverages_results = []
skip_tests = false
stars = 2
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324806.186339

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
qiskit_version = "0.44.1"
timestamp = 1696324881.422711

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
qiskit_version = "0.44.1"
timestamp = 1696324376.489632

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
qiskit_version = "0.44.1"
timestamp = 1696324880.02079

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778455"
qiskit_version = "0.44.0"
timestamp = 1692695810.332834

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
qiskit_version = "0.44.1"
timestamp = 1696324376.489632

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
qiskit_version = "0.44.1"
timestamp = 1696324880.02079

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390977032"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324806.186339

