name = "QoptKIT"
url = "https://github.com/SOQCSAdmin/QoptKIT"
description = "Optical circuits in Qiskit. Translate Qiskit circuits to quantum-optical circuits made of phase shifters and beamsplitters, simulate the circuit, then translate the outcome back to a qubit encoding."
licence = "Apache License 2.0"
contact_info = "soqcslib@gmail.com"
alternatives = "_No response_"
affiliations = "National University of Ireland Maynooth"
labels = [ "Circuit simulator",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
group = "other"
documentation = "https://soqcsadmin.github.io/QoptKIT/"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254834"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396943.597615

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254834"
qiskit_version = "0.45.1"
timestamp = 1705396841.692577

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254834"
qiskit_version = "0.45.1"
timestamp = 1705396972.233655

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254834"
qiskit_version = "0.45.1"
timestamp = 1705396972.233655

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254834"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396943.597615

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254834"
qiskit_version = "0.45.1"
timestamp = 1705396841.692577

