name = "Quantum Prototype Template"
url = "https://github.com/qiskit-community/quantum-prototype-template"
description = "A template repository for generating new quantum prototypes based on Qiskit."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "Qiskit Community"
labels = [ "Productivity",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 38
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396956.724283

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
qiskit_version = "0.45.1"
timestamp = 1705396981.291415

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
qiskit_version = "0.45.1"
timestamp = 1705396862.464758

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
qiskit_version = "0.45.1"
timestamp = 1705396980.305398

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547908"
qiskit_version = "0.44.1"
timestamp = 1695720212.075357

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547908"
qiskit_version = "0.44.1"
timestamp = 1695720562.501782

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545036052"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534312.675789

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759502"
qiskit_version = "0.44.2"
timestamp = 1698139842.497136

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759502"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139814.918496

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759502"
qiskit_version = "0.44.2"
timestamp = 1698139442.025867

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
qiskit_version = "0.45.1"
timestamp = 1705396862.464758

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
qiskit_version = "0.45.1"
timestamp = 1705396980.305398

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539255181"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396956.724283

