name = "Quantum-enhanced-variational-autoencoder"
url = "https://github.com/Anantha-Rao12/Quantum-enhanced-variational-autoencoder"
description = "- This is a submission for the Qiskit Ecosystem. - The project is the source code for building and running a hybrid quantum-classical neural network for generative modeling. - The code is a qiskit implementation of a quantum-enhanced variational autoencoder (QeVAE). - The project is based on the research paper \"Learning hard distributions with quantum-enhanced Variational Autoencoders\" by Rao et al. (https://arxiv.org/abs/2305.01592)."
licence = "Apache License 2.0"
contact_info = "anantharao@zohomail.in"
alternatives = "_No response_"
affiliations = "Indian Institute of Science Education and Research IBM Research India"
labels = [ "paper implementation",]
tier = "Community"
website = "https://anantha-rao12.github.io"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
