name = "quantum-prototype-template"
url = "https://github.com/qiskit-community/quantum-prototype-template"
description = "A template repository for generating new quantum prototypes based on Qiskit."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "Qiskit Community"
labels = [ "Productivity",]
tier = "Community"
website = "https://github.com/qiskit-community/quantum-prototype-template"
styles_results = []
coverages_results = []
skip_tests = false
stars = 35
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324723.345043

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
qiskit_version = "0.44.1"
timestamp = 1696324759.123056

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
qiskit_version = "0.44.1"
timestamp = 1696324330.153124

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
qiskit_version = "0.44.1"
timestamp = 1696324757.738295

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
qiskit_version = "0.44.1"
timestamp = 1696324330.153124

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
qiskit_version = "0.44.1"
timestamp = 1696324757.738295

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975950"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324723.345043

