name = "quPython"
url = "https://github.com/frankharkins/quPython"
description = "Write quantum programs as Python functions instead of circuit objects. Create higher-level quantum data types and return measurement results as bool-like objects."
licence = "MIT license"
contact_info = "frankharkins@hotmail.co.uk"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Circuit", "Converter", "Productivity",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 1
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251865"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = "unknown"
timestamp = 1705396240.678257

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251865"
qiskit_version = "unknown"
timestamp = 1705396233.658124

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251865"
qiskit_version = "unknown"
timestamp = 1705396247.322318

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251865"
qiskit_version = "unknown"
timestamp = 1705396247.322318

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251865"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = "unknown"
timestamp = 1705396240.678257

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539251865"
qiskit_version = "unknown"
timestamp = 1705396233.658124

