name = "SQuADDS"
url = "https://github.com/LFL-Lab/SQuADDS"
description = "A validated design database and simulation workflow software for superconducting qubit design"
licence = "MIT license"
contact_info = "shanto@usc.edu"
alternatives = "_No response_"
affiliations = "Levenson-Falk Lab, University of Southern California"
labels = [ "Hardware",]
tier = "Community"
website = "https://lfl-lab.github.io/SQuADDS/index.html"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
